WITH DATE_DIM AS
(
SELECT
TO_TIMESTAMP(STARTED_AT) as STARTED_AT,
DATE(TO_TIMESTAMP(STARTED_AT)) as DATE_START_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) as HOUR_START_AT,

{{day_type('STARTED_AT')}} AS DAY_TYPE,
{{get_season('STARTED_AT')}} AS SEASON_OF_YEAR

FROM {{ source('demo', 'biketable') }}
where STARTED_AT!= 'started_at' )

SELECT * FROM DATE_DIM


