WITH bikes AS (
SELECT 
RIDE_ID,
--RIDEABLE_TYPE,
DATE(TO_TIMESTAMP(STARTED_AT)) as TRIP_DATE,
START_STATIO_ID as station_id,
END_STATION_ID,
MEMBER_CSUAL AS MEMBER_CASUAL,
TIMESTAMPDIFF(SECOND,TO_TIMESTAMP(STARTED_AT),TO_TIMESTAMP(ENDED_AT)) AS TRIP_DURATION_SECONDS

FROM {{ ref('stage_bike') }}
WHERE RIDE_ID!='ride_id'

)

select * from bikes